name: first

on: 
  push:
    branches:
      - master

# comment23
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two 
      run: env | sort 

  job2:
    name: Second job
    needs: job1
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two 
      run: "gci env: | sort name"
